// <auto-generated>
using System.Reflection;

namespace FxResources.Microsoft.Extensions.Logging
{
    internal static class SR { }
}
namespace System
{
    internal static partial class SR
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(FxResources.Microsoft.Extensions.Logging.SR)));

        /// <summary>{0} is invalid ActivityTrackingOptions value.</summary>
        internal static string @InvalidActivityTrackingOptions => GetResourceString("InvalidActivityTrackingOptions", @"{0} is invalid ActivityTrackingOptions value.");

    }
}
